services:
  order_app_grpc:
    container_name: 'order_app_grpc'
    build:
      context: .
      dockerfile: Dockerfile-roadrunner
    ports:
      - 9002:80
    volumes:
      - ./order-app/grpc-server:/var/www/html