# ROADRUNNER GIT https://github.com/roadrunner-server/roadrunner/pkgs/container/roadrunner
FROM ghcr.io/roadrunner-server/roadrunner:2023.2.0 AS roadrunner
FROM php:8.1-cli

WORKDIR /var/www/html

#COPY ROADRUNNER DEFAULT CONFIG AND BINARY
COPY --from=roadrunner /usr/bin/rr /usr/local/bin/rr

ENV COMPOSER_ALLOW_SUPERUSER=1
COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
CMD bash -c "composer install"

CMD rr serve -c /var/www/html/.rr.yaml