version: '3'
rpc:
    listen: 'tcp://127.0.0.1:6001'
server:
  command: "php grpc-worker.php"
grpc:
  listen: "tcp://127.0.0.1:9001"
  pool:
    allocate_timeout: 5s
  proto:
    - "proto/pinger.proto"

#metrics:
#    address: '127.0.0.1:2112'
