version: '3'

server:
  command: "php worker.php"
  relay: "pipes"
  relay_timeout: "20s"

grpc:
  listen: "tcp://0.0.0.0:2000"
  proto:
    - proto/user.proto
  max_send_msg_size: 50
  max_recv_msg_size: 50
  max_connection_idle: 0s
  max_connection_age: 0s
  max_connection_age_grace: 0s
  max_concurrent_streams: 10
  ping_time: 1s
  timeout: 200s
  pool:
    num_workers: 2
    max_jobs: 0
    allocate_timeout: 60s
